name: date_and_time_example
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.6.1


dependencies:
  date_and_time: 
    path: ../

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
