name: date_and_time
description: Clean, immutable Date and Time types. Separate types without the complexity of DateTime.
version: 0.0.4-alpha
repository: https://github.com/MelbourneDeveloper/date_and_time

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:

dev_dependencies:
  austerity: ^1.2.0
  lints: ^5.0.0
  test: ^1.24.0

topics:
  - date
  - time
  - datetime
  - testing
  - utilities
